事業をエンジニアリングしよう ②実装
u-toru42/mokumoku pull request #2
Opened 2022-11-16 11:38 UTC by u-toru42

RSpecの結果です。
![スクリーンショット 2022-11-16 20 28 27](https://user-images.githubusercontent.com/37538568/202169030-07f47827-5e6e-40a2-8608-892da2713e53.png)
プロフィール画面にhobby, profileの欄を追加しました。
![スクリーンショット 2022-11-16 20 35 04](https://user-images.githubusercontent.com/37538568/202170269-f01cc85d-d823-419d-8fba-aad416e68170.png)
イベント画面から遷移できるプロフィール画面です。フォローボタンに合わせてフォロワー数が増減します。
![スクリーンショット 2022-11-16 20 30 29](https://user-images.githubusercontent.com/37538568/202169279-6cae7f86-2006-4d12-9590-f08762fff99c.png)
マイページに自分のフォロー/フォロワーのリンクを貼りました。
![スクリーンショット 2022-11-16 20 31 58](https://user-images.githubusercontent.com/37538568/202169602-e16111af-dab3-4ee0-99c2-2b01b3f7b0cb.png)
フォロー一覧画面です。
![スクリーンショット 2022-11-16 20 33 14](https://user-images.githubusercontent.com/37538568/202169883-db76f163-17cd-4125-b786-396c21777899.png)
フォロワー一覧画面です。
![スクリーンショット 2022-11-16 20 33 52](https://user-images.githubusercontent.com/37538568/202170017-569f81f8-ad98-4573-9613-4280f386fe52.png)

2022-11-17 04:32 UTC, Tsuchiya2 reviewed
一旦気になる部分をコメントしました。

2022-11-17 04:32 UTC, Tsuchiya2 commented on app/controllers/profiles_controller.rb
> +    @user = User.find_by(id: params[:id])
idを探し出す際はfind_byではなく、もっと別なメソッドの方が良いですね。

2022-11-17 04:32 UTC, Tsuchiya2 commented on app/decorators/profile_decorator.rb
> +  delegate_all
使っていないようでしたら削除しておきましょう。（他の箇所も同様です）

2022-11-17 04:32 UTC, Tsuchiya2 commented on app/views/events/_attendee.html.erb
> +    <%= link_to attendee.name, profile_path(attendee.id) %>
`attendee.id`と記載するのはあまりしないですね。
オブジェクトを渡しても同じ結果になると思うので修正しましょう。（他の箇所も同様です）

2022-11-17 04:32 UTC, Tsuchiya2 commented on app/views/shared/_header.html.erb
> +          </li>
削除のし忘れですかね？

2022-11-17 04:32 UTC, Tsuchiya2 commented on app/views/users/followers.html.erb
> +      <% @users.each do |user| %>
eachで回して表示ではなく、collectionを使った方がパフォーマンスが良さそうです。（他の箇所も同様です）

2022-11-17 04:32 UTC, Tsuchiya2 commented on app/controllers/profiles_controller.rb
> +  end
どのアクションでもユーザーレコードを呼び出しているので共通化しましょう。
また、@following_users, @follower_userも共通化できそうです。（似たような他のファイルも同様です）

2022-11-17 09:57 UTC, u-toru42 commented on app/controllers/profiles_controller.rb
> +  end
処理を共通化し、メモ化しました。また、@following_users, @follower_userを共通化しました。profiles_controller.rbのshowメソッドは不要なので削除しました。
3140a24198dcf989f11ea63eb47dc48f62b7bd63

2022-11-17 09:57 UTC, u-toru42 commented on app/views/users/followers.html.erb
> +      <% @users.each do |user| %>
collectionで実装しました。
4c80e84f43b4ae0e9f89843133ad14325442e3ad

2022-11-17 09:57 UTC, u-toru42 commented on app/views/shared/_header.html.erb
> +          </li>
ご指摘頂きましたので、削除のし忘れを修正しました。
3de0487082370a28923208f383e74e07b1a918ba>こちらで対応を行いました。

2022-11-17 09:57 UTC, u-toru42 commented on app/views/events/_attendee.html.erb
> +    <%= link_to attendee.name, profile_path(attendee.id) %>
idの記載を修正しました。オブジェクトを渡して処理します。
3e0b5f959ae4599ac3572ca449ff389953b83793

2022-11-17 09:57 UTC, u-toru42 commented on app/decorators/profile_decorator.rb
> +  delegate_all
ご指摘頂きましたので、profileとrelationshipのdecorator.rbを削除しました。
a242afbf394bfb1bd0999a1725ecb41bbe8327ae

2022-11-17 09:57 UTC, u-toru42 commented on app/controllers/profiles_controller.rb
> +    @user = User.find_by(id: params[:id])
ご指摘頂きましたので、find_byからメソッドをfindに変え、メモ化してDB負荷を下げました。
3140a24198dcf989f11ea63eb47dc48f62b7bd63

2022-11-17 10:21 UTC, busitora requested changes

2022-11-17 10:21 UTC, busitora commented on app/views/users/followers.html.erb
> +<div class="cover-user-index">
app/views/users/follows.html.erb と同じであれば共通化できますね

2022-11-17 10:21 UTC, busitora commented on app/controllers/concerns/profile_follow.rb
> +require 'active_support'
インスタンス変数を使わないように実装できますか？

2022-11-18 01:26 UTC, u-toru42 commented on app/views/users/followers.html.erb
> +<div class="cover-user-index">
ご指摘頂きましたので、follows、followersのビューを render partialを使い、共通化しました。
d925c51a60a8d64a99c6c5f4bd325dced98bc66c>こちらで対応を行いました。

2022-11-20 11:11 UTC, u-toru42 commented on app/controllers/concerns/profile_follow.rb
> +require 'active_support'
ご指摘頂きましたので、インスタンス変数の@following_users, @follower_userを使わずに、@user、@usersで管理できるように実装致しましたが、こちらの理解で合っておりますでしょうか。
b48381b70038021c029e7f6b851a7744f27088f8>こちらで対応を行いました。

2022-11-20 23:49 UTC, busitora commented on app/controllers/concerns/profile_follow.rb
> +require 'active_support'
app/controllers/concerns/follow_profile.rb に対してですね！

controllerで使う分には問題ないです！

2022-11-21 07:50 UTC, u-toru42 commented on app/controllers/concerns/profile_follow.rb
> +require 'active_support'
お世話になっております。遅まきながら、ご指示の内容を理解できた気がします。
これまでconcerns内でコントローラの処理をまとめるという概念に縛られていたため、変数なしでユーザーレコードの呼び出しの処理のみを実装するという考えに至れず、ご迷惑をおかけしました。
f02b11c075e7deba42a3b1a6e1609909f0ccfef1>こちらで対応を行いました。

2022-11-21 10:05 UTC, busitora commented
LGTM！

2022-11-21 10:11 UTC, u-toru42 commented
> LGTM！

ありがとうございます！

2022-11-21 10:11 UTC, merged